# Generated by Django 4.2.1 on 2023-05-26 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_img_url', models.URLField(null=True)),
                ('company', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_profile', models.ManyToManyField(blank=True, related_name='featured_profiles_custom', to='home.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlists_custom', to='home.userprofile')),
            ],
        ),
    ]
