# Generated by Django 4.2.1 on 2023-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clintprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintprofile',
            name='featured_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='featured_profiles_custom', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists_custom', to='home.userprofile'),
        ),
    ]
